#!/bin/bash

echo "StingRay's Total Dark Theme for CWP"
echo "###################################"
echo ""
cd /usr/local/cwpsrv/htdocs/admin/design/css
chmod 777 custom.css
echo "" >> custom.css
echo "html,.deleted" >> custom.css
echo "{" >> custom.css
echo "background:#000;" >> custom.css
echo "-webkit-filter:invert(1) hue-rotate(180deg)!important;" >> custom.css
echo "-moz-filter:invert(1) hue-rotate(180deg)!important;" >> custom.css
echo "filter:invert(1) hue-rotate(180deg)!important;" >> custom.css
echo "filter:progid:DXImageTransform.Microsoft.BasicImage(grayscale=0,xray=0,mirror=0,invert=1,opacity=1,rotation=2)!important;" >> custom.css
echo "-webkit-transition:100ms ease all;" >> custom.css
echo "transition:100ms ease all;" >> custom.css
echo "-o-transition-duration:100ms ease all" >> custom.css
echo "}" >> custom.css
echo "" >> custom.css
echo "iframe,img,embed[flashvars],[type*=\"application/x-shockwave-flash\"],[type*=\"application/x-silverlight\"]" >> custom.css
echo "{" >> custom.css
echo "-webkit-filter:invert(1) hue-rotate(180deg)!important;" >> custom.css
echo "-moz-filter:invert(1) hue-rotate(180deg)!important;" >> custom.css
echo "filter:invert(1) hue-rotate(180deg)!important;" >> custom.css
echo "filter:progid:DXImageTransform.Microsoft.BasicImage(grayscale=0,xray=0,mirror=0,invert=1,opacity=1,rotation=2)!important;" >> custom.css
echo "opacity:.4" >> custom.css
echo "}" >> custom.css
echo "" >> custom.css
echo "tr > td > a > img,th > a > img" >> custom.css
echo "{" >> custom.css
echo "filter:url(\"data:image/svg+xml;utf8,<svg xmlns=\'http://www.w3.org/2000/svg\'><filter id=\'invert\'><feColorMatrix type=\'matrix\' values=\'-1 0 0 0 1 0 -1 0 0 1 0 0 -1 0 1 0 0 0 1 0\'/></filter></svg>#invert\")!important;-webkit-filter:hue-rotate(180deg)!important;" >> custom.css
echo "filter:hue-rotate(180deg)!important;" >> custom.css
echo "filter:progid:DXImageTransform.Microsoft.BasicImage(grayscale=0,xray=0,mirror=0,invert=0,opacity=1,rotation=2)!important" >> custom.css
echo "}" >> custom.css
echo "" >> custom.css
